### ISSUE TITLE
crash after adding lib

### ISSUE THREAD

**Issue by androidlover5842** [AdevintaSpain/Leku#236]
app works fine after removing lib .
my build.gradle https://hastebin.com/akowetoraz.php

> 2019-03-22 18:09:15.621 20588-20588/androidlover5842.proto.oMachanicAdmin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: androidlover5842.proto.oMachanicAdmin, PID: 20588
    android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class com.google.android.material.textfield.TextInputLayout
    Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.google.android.material.textfield.TextInputLayout
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidlover5842.proto.oMachanicAdmin.Fragment.FragmentAddStore.onCreateView(FragmentAddStore.java:95)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2530)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:688)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2069)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1859)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:116)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:409)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:388)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at androidlover5842.proto.oMachanicAdmin.Fragment.FragmentAddStore.onCreateView(FragmentAddStore.java:95) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2530) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:688) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2069) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1859) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721) 
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by ferranpons** [comment]
Hi @androidlover5842 

Please could you provide more info about your problem?

Describe the bug

To Reproduce Steps to reproduce the behavior:

Expected behavior

Info Required

Which version of the library do you actually use?

Do you have the localization permission granted?

Are you sending parameters to the activity through the bundle?

Android monitor shows any log related to the library when the error is shown?

Any other thing that could help me to reproduce the error?

Screenshots

Smartphone:

Device: [e.g. Samsung S8]
Additional context

**Comment by androidlover5842** [comment]
if i add editText on main fragment and set onclick listener to start lekus map activity it will crash when app starts and i used V6.1.1 and yes all permissions where granted on login screen before main activity starts .
I will try taking screenshots soon

**Comment by ferranpons** [comment]
Ok, but I still need more info to try to reproduce the problem.

Please could you tell me on which device are you experiencing this problem? And the version of the Android API (21, 23, 26, 28)?  

Are you overriding the AndroidX versions for the appcompat and other libraries?

**Comment by androidlover5842** [comment]
i tried it on nokia 1 and pixel 3 xl both have api 28 and no i was not overriding AndroidX,i might have removed lib before reporting issue so its not in build.gradle but i added it after squareup.okhttp3 and i will try to reproduce problem at night with latest AndroidX libs
