### ISSUE TITLE
java.lang.NoClassDefFoundError: com.schibstedspain.leku.LocationPickerActivity

### ISSUE THREAD

**Issue by mumia7575** [AdevintaSpain/Leku#258]
**Description**
Running this library with R8 enabled (`minifyEnabled true`) without multidex enable.
Getting a crash with `java.lang.NoClassDefFoundError` exception.
Same behavior with the following proguard rules:
```
-keep class com.schibstedspain.leku.** { *; }
-dontwarn com.schibstedspain.leku.**

-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
```

**To Reproduce**
Instantiate a new object via `LocationPickerActivity.Builder()`.

**Expected behavior**
No crash.

**Info Required**
- Which version of the library do you actually use?
`com.schibstedspain.android:leku:6.2.1`

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?
No.

- Android monitor shows any log related to the library when the error is shown?
```
java.lang.NoClassDefFoundError: com.schibstedspain.leku.LocationPickerActivity
        at com.schibstedspain.leku.LocationPickerActivity$Builder.build(LocationPickerActivity.kt:1290)
        at pt.comp.app.Fragment.onGPSClick(Fragment.kt:69)
        at pt.comp.app.adapters.Adapter$SendViewHolder$setup$3.onClick(Adapter.kt:69)
        at android.view.View.performClick(View.java:5246)
        at android.widget.TextView.performClick(TextView.java:10566)
        at android.view.View$PerformClick.run(View.java:21256)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6917)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

- Any other thing that could help me to reproduce the error?
No.

**Smartphone:**
 - Every Smartphone

**Comment by ferranpons** [comment]
Hi @mumia7575 

Have you tried with multidex enabled?

**Comment by mumia7575** [comment]
Not excluding the following group resolved the issue:
`exclude group: 'com.google.android.gms'`

Working result:
```
implementation ('com.schibstedspain.android:leku:6.2.1'){
    exclude group: 'androidx.appcompat'
}
```

Another question, when I click on the map, it registers a marker and zooms out. Is there any option to disable the zoom out? Should I open an enhancement ticket if it is not possible?

**Comment by ferranpons** [comment]
Closing as Solved
