### ISSUE TITLE
GooglePlacesDataSource.java line 57 (Fatal Exception: java.lang.IllegalStateException: Task is not yet complete)

### ISSUE THREAD

**Issue by mayurwish** [AdevintaSpain/Leku#266]
## Description
Fatal Exception: java.lang.IllegalStateException: Task is not yet complete
       at com.google.android.gms.internal.clearcut.zzax.zzb(zzax.java:21)
       at com.google.android.gms.internal.clearcut.zzk.zzb(zzk.java:21)
       at com.google.android.gms.common.internal.Preconditions.checkState + 29(Preconditions.java:29)
       at com.google.android.gms.tasks.zzu.zzb + 121(zzu.java:121)
       at com.google.android.gms.tasks.zzu.getResult + 12(zzu.java:12)
       at com.schibstedspain.leku.geocoder.places.GooglePlacesDataSource.getAddressListFromPrediction + 57(GooglePlacesDataSource.java:57)
       at com.schibstedspain.leku.geocoder.places.GooglePlacesDataSource.access$getAddressListFromPrediction + 23(GooglePlacesDataSource.java:23)
       at com.schibstedspain.leku.geocoder.places.GooglePlacesDataSource$getFromLocationName$1.call + 38(GooglePlacesDataSource.java:38)
       at com.schibstedspain.leku.geocoder.places.GooglePlacesDataSource$getFromLocationName$1.call + 23(GooglePlacesDataSource.java:23)
       at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual + 33(ObservableDefer.java:33)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual + 44(ObservableFlattenIterable.java:44)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableTake.subscribeActual + 30(ObservableTake.java:30)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableToList.subscribeActual + 51(ObservableToList.java:51)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableOnErrorReturn.subscribeActual + 31(ObservableOnErrorReturn.java:31)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe + 110(ObservableZip.java:110)
       at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual + 72(ObservableZip.java:72)
       at io.reactivex.Observable.subscribe + 12267(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run + 96(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run + 578(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run + 66(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call + 57(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run + 237(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 272(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1133(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 607(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run + 760(Thread.java:760)

## Info Required

- Which version of the library do you actually use? 6.2.1

- Do you have the localization permission granted? Yes

- Are you sending parameters to the activity through the bundle? Nope

- Could you describe what are the actions do you make to raise that error? Nope

- Android monitor shows any log related to the library when the error is shown? Yes as provided above

- Any other thing that could help me to reproduce the error? Nope

**Comment by ferranpons** [comment]
@mayurwish looks like a weird issue. It seems like the response took longer than it should that's why it crashed. But It only depends on the own Places service.
Since the Google Places SDK was deprecated it could be possible that their API is not working correctly or the version used has some kind of issue.

Please could you try the latest version of this library (6.3.0)? Because we have updated all the Play Services libraries versions and maybe that could help. If not, please let me know.

Many thanks!

**Comment by ferranpons** [comment]
Try the new version v7.0.0
