### ISSUE TITLE
Inflater error?

### ISSUE THREAD

**Issue by Thomar10** [AdevintaSpain/Leku#290]
When Im trying to open the map I get this inflater error. Am I doing something wrong?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.project.socker, PID: 21788
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.project.socker/com.schibstedspain.leku.LocationPickerActivity}: android.view.InflateException: Binary XML file line #9 in com.project.socker:layout/leku_activity_location_picker: Binary XML file line #9 in com.project.socker:layout/leku_activity_location_picker: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #9 in com.project.socker:layout/leku_activity_location_picker: Binary XML file line #9 in com.project.socker:layout/leku_activity_location_picker: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #9 in com.project.socker:layout/leku_activity_location_picker: Error inflating class fragment
     Caused by: java.lang.RuntimeException: The API key can only be specified once. It is recommended that you use the meta-data tag with the name: com.google.android.geo.API_KEY in the <application> element of AndroidManifest.xml
        at com.google.maps.api.android.lib6.drd.q.b(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):5)
        at com.google.maps.api.android.lib6.auth.f.a(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):16)
        at com.google.maps.api.android.lib6.impl.g.a(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):59)
        at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):7)
        at com.google.android.gms.maps.internal.CreatorImpl.newMapFragmentDelegate(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):30)
        at com.google.android.gms.maps.internal.h.a(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):51)
        at cl.onTransact(:com.google.android.gms.dynamite_mapsdynamite@19629084@19.6.29 (120700-0):5)
        at android.os.Binder.transact(Binder.java:914)
        at com.google.android.gms.internal.maps.zza.zza(Unknown Source:10)
        at com.google.android.gms.maps.internal.zzf.zzc(Unknown Source:5)
        at com.google.android.gms.maps.SupportMapFragment$zzb.zzd(Unknown Source:12)
        at com.google.android.gms.maps.SupportMapFragment$zzb.createDelegate(Unknown Source:6)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(com.google.android.gms:play-services-base@@17.1.0:18)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onInflate(com.google.android.gms:play-services-base@@17.1.0:20)
        at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source:21)
        at androidx.fragment.app.Fragment.onInflate(Fragment.java:1488)
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3204)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:336)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)

**Comment by ferranpons** [comment]
Hi @Thomar10 

Please, could you provide more info about the issue? It's difficult for me to know what is happening if you only provide the error log.
How do I reproduce it?
Which version of the library are you using?
Are you using a device or the emulator?
Are you providing all the dependencies needed?
