### ISSUE TITLE
com.schibstedspain.leku.geocoder.api.NetworkException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd486a5b8: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by changjiashuai** [AdevintaSpain/Leku#310]
**Info Required**
- Which version of the library do you actually use?
leku version v7.2.0

- Any other thing that could help me to reproduce the error?
start LocationPickerActivity.

**Smartphone:**
 - Device: [e.g. OnePlus 7 Pro]

**Additional context**
    --------- beginning of crash
2020-09-21 14:58:49.940 14808-15010/com.imile.iorder E/AndroidRuntime: FATAL EXCEPTION: RxNewThreadScheduler-8
    Process: com.imile.iorder, PID: 14808
    io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.schibstedspain.leku.geocoder.api.NetworkException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd486a5b8: I/O error during system call, Connection reset by peer
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.schibstedspain.leku.geocoder.GoogleGeocoderDataSource$getFromLocation$1.subscribe(GoogleGeocoderDataSource.kt:87)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:96)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onError(ObservableRetryPredicate.java:79)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84)
        at com.schibstedspain.leku.geocoder.AndroidGeocoderDataSource$getFromLocation$1.subscribe(AndroidGeocoderDataSource.kt:42)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.schibstedspain.leku.geocoder.api.NetworkException: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd486a5b8: I/O error during system call, Connection reset by peer
        at com.schibstedspain.leku.geocoder.api.NetworkClient.requestFromLocationName(NetworkClient.kt:38)
        at com.schibstedspain.leku.geocoder.GoogleGeocoderDataSource$getFromLocation$1.subscribe(GoogleGeocoderDataSource.kt:77)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40) 
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:96) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableRetryPredicate$RepeatObserver.onError(ObservableRetryPredicate.java:79) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84) 
        at com.schibstedspain.leku.geocoder.AndroidGeocoderDataSource$getFromLocation$1.subscribe(AndroidGeocoderDataSource.kt:42) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40) 
        at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13099) 
        at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd486a5b8: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2020-09-21 14:58:49.941 14808-15010/com.imile.iorder E/AndroidRuntime:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at com.schibstedspain.leku.geocoder.api.NetworkClient.requestFromLocationName(NetworkClient.kt:27)
        	... 19 more

**Comment by ferranpons** [comment]
Please, try the latest version 9.1.1. That version is not maintained any more. Sorry for the inconvenience.

**Comment by fukemy** [comment]
im using v 9.1.1 and got error due to resource v31 not found

**Comment by steve47457** [comment]
I also get this error.
