### ISSUE TITLE
NullPointerException throws on click of search items 

### ISSUE THREAD

**Issue by gobinda99** [AdevintaSpain/Leku#327]
java.lang.NullPointerException: {
                address.thoroughfare
            } must not be null
        at com.adevinta.leku.LocationPickerActivity.getFormattedAddress(LocationPickerActivity.kt:1051)
        at com.adevinta.leku.LocationPickerActivity.setLocationInfo(LocationPickerActivity.kt:1038)
        at com.adevinta.leku.LocationPickerActivity.setNewLocation(LocationPickerActivity.kt:1372)
        at com.adevinta.leku.LocationPickerActivity.access$setNewLocation(LocationPickerActivity.kt:120)
        at com.adevinta.leku.LocationPickerActivity$setUpResultsList$2.onItemClick(LocationPickerActivity.kt:378)
        at com.adevinta.leku.LocationSearchAdapter$SearchViewHolder.onClick(LocationSearchAdapter.kt:22)

**Comment by gobinda99** [comment]
The return type of the function should be String? 

 private fun getFormattedAddress(address: Address): String? {
        return if (address.subThoroughfare.isNullOrEmpty()) {
            address.thoroughfare
        } else {
            getString(R.string.leku_formatted_address, address.thoroughfare, address.subThoroughfare)
        }
    }

**Comment by ferranpons** [comment]
Solved in the new version 9.1.1
