### ISSUE TITLE
2 errors in newest version (9.1.3)

### ISSUE THREAD

**Issue by steve47457** [AdevintaSpain/Leku#342]
I still get the 2 errors that always occur and I believe they can easily be fixed.

Error 1 (Event type ANR): 

```
main (waiting): tid=1 systid=22477
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:387)
       at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java)
       at com.adevinta.leku.geocoder.timezone.GoogleTimeZoneDataSource.getTimeZone(GoogleTimeZoneDataSource.java)
       at com.adevinta.leku.geocoder.GeocoderPresenter.returnTimeZone(GeocoderPresenter.java)
       at com.adevinta.leku.geocoder.GeocoderPresenter.getInfoFromLocation$lambda-18(GeocoderPresenter.java)
       at com.adevinta.leku.geocoder.GeocoderPresenter.$r8$lambda$1LPQuC9JhTvH0Af6K5P9wwLq_Yw(GeocoderPresenter.java)
       at com.adevinta.leku.geocoder.GeocoderPresenter$$InternalSyntheticLambda$1$2726b4a0010c7a0503327eb77e244f5efee13131e58dd98511fe97a36f6fa9ce$2.apply(GeocoderPresenter.java)
       at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess(MaybeFlatten.java)
       at io.reactivex.rxjava3.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java)
       at io.reactivex.rxjava3.internal.operators.maybe.MaybeFilterSingle$FilterMaybeObserver.onSuccess(MaybeFilterSingle.java)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableSingleSingle$SingleElementSubscriber.onComplete(FlowableSingleSingle.java)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.onComplete(FlowableRetryPredicate.java)
       at io.reactivex.rxjava3.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java)
       at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java)
       at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java)
       at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8506)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Error 2 (Event type Crash):

```
Fatal Exception: b5.e: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException: grpc failed
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:19)
       at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:49)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:7)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:14)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:6)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:33)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:22)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:14)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:9)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:9)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:2)
       at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:9)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:13)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
	   
	   --
	  
```
Caused by java.io.IOException: grpc failed
       at android.location.Geocoder.getFromLocation(Geocoder.java:136)
       at com.adevinta.leku.geocoder.AndroidGeocoderDataSource.getFromLocation$lambda-2(AndroidGeocoderDataSource.java:10)
       at com.adevinta.leku.geocoder.AndroidGeocoderDataSource.$r8$lambda$HojMsADA4eEesXlzlsEapFssVOU(AndroidGeocoderDataSource.java)
       at com.adevinta.leku.geocoder.AndroidGeocoderDataSource$$InternalSyntheticLambda$2$3bff7d51e4e809dc309864694a0c3601036f3f908be6956c0d332efa30a9e68e$0.call(AndroidGeocoderDataSource.java:6)
       at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:16)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:7)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:14)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:6)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:33)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:22)
       at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:14)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:9)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:9)
       at io.reactivex.rxjava3.core.Single.subscribe(Single.java:14)
       at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:2)
       at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:9)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:13)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by fukemy** [comment]
Hi, new version 9.1.4 pushed, could you @steve47457  please test it, im stucking in IOS work
