### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1

### ISSUE THREAD

**Issue by steve47457** [AdevintaSpain/Leku#375]
Hi :) How can I fix this crash that happens sometimes?

Android versions: multiple.
Devices: multiple.
Device state: 0% background.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.adevinta.leku.LocationPickerActivity$setUpResultsList$2.onItemClick(LocationPickerActivity.java:6)
       at com.adevinta.leku.LocationSearchAdapter$SearchViewHolder.onClick(LocationSearchAdapter.java:6)
       at android.view.View.performClick(View.java:7585)
       at android.view.View.performClickInternal(View.java:7541)
       at android.view.View.access$3900(View.java:842)
       at android.view.View$PerformClick.run(View.java:28877)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8194)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
       
Thanks.

**Comment by ferranpons** [comment]
@steve47457 which version of the library are you using? Looks like the code that this crash references does not longer exists. Please assure that you are using the latest version.

**Comment by ferranpons** [comment]
@steve47457 Looks like this has no response. So I close it.
